import data from './model-cases-data.js';

export function renderModelCases(zh) {
  const t = (en, cn) => zh ? cn : en;
  const esc = v => String(v).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const image = (id, title, description) => {
    const frame = data.images.find(i => i.id === id);
    return `<figure><h3>${title}</h3><a class="image-link" href="${esc(frame.image)}" target="_blank" rel="noopener" aria-label="${esc(title + ' · ' + t('open original', '查看原图'))}"><img src="${esc(frame.image)}" width="1024" height="1024" alt="${esc(description)}" loading="lazy"></a><figcaption><span>${esc(frame.model)}</span><span>${t('Original ↗', '原图 ↗')}</span></figcaption><p class="model-caption">${description}</p></figure>`;
  };
  return `<section class="case model-case" id="model-cases" aria-labelledby="model-cases-title">
    <div class="case-heading"><div><p class="case-number">QWEN / FLUX · ${data.date}</p><h2 id="model-cases-title">${t('Photographic detail. Controlled layout.', '写实质感，与布局控制。')}</h2><p class="case-description">${t('A three-object scene with a traffic barrier, electric kettle and shopping cart. Original Qwen and FLUX outputs show the trade-off between visual richness and layout fidelity.', '同一组三物体：路障、电热水壶与购物车。保留 Qwen 和 FLUX 的原始输出，分开观察画面质感与布局还原。')}</p></div><span class="badge partial">${t('Tuning case · experiment not promoted', '调参案例 · 实验未晋级')}</span></div>
    <div class="comparison">${image('qwen-free', t('Qwen · without depth', 'Qwen · 无深度控制'), t('Metallic kettle and detailed cart in a photographic street scene; layout is not aligned to the reference.', '金属水壶与购物车细节清楚，背景更接近街景照片；布局未对齐参考。'))}${image('qwen-depth', t('Qwen · depth scale 1.2', 'Qwen · 深度控制 1.2'), t('Same model, different control setting. This is a configuration comparison, not successive repair rounds.', '同一模型的另一配置。材质与背景仍较写实，但这是参数对比，不是连续修复轮次。'))}</div>
    <h3 class="model-subtitle">${t('FLUX baseline → retry', 'FLUX 初始配置 → 重试配置')}</h3>
    <div class="comparison">${image('flux-before', t('Before · spatial prompt', '修改前 · spatial 提示词'), t('Depth-conditioned generation follows the object cluster, but the kettle body appears rounded and ambiguous.', '深度约束下，主体簇更接近参考布局；水壶壶身偏圆，形状表达含糊。'))}${image('flux-after', t('After · simple prompt', '修改后 · simple 提示词'), t('The kettle body and handle are clearer in this image. The cart and barrier remain visible; this does not establish complete acceptance.', '本图中壶身与把手更明确，购物车和路障仍可见；这不等于完整要求均已通过。'))}</div>
    <div class="process"><div><h3>${t('01 / What changed', '01 / 改了什么')}</h3><p>${t('The archived FLUX comparison changes the prompt variant from spatial to simple. Images are regenerated, not retouched.', '归档 FLUX 对比将提示词版本从 spatial 改为 simple。这里是重新生成的原始结果，不是修图。')}</p></div><div><h3>${t('02 / What improved', '02 / 能看见什么')}</h3><p>${t('The kettle silhouette is easier to recognize in the retry. This is a visual observation, not an isolated causal claim or an evaluator score.', '重试结果中的水壶轮廓更容易辨认。这是原图目检结论，不是单变量因果结论，也不是评测器分数。')}</p></div><div><h3>${t('03 / What remains', '03 / 保留哪些边界')}</h3><p>${t('The source report still marks the three-case experiment blocked. No new VLM score, training gain or production-readiness claim is made.', '原报告仍将三案例整体实验标为 blocked。不补造 VLM 分数，不宣称训练提升或已满足生产门槛。')}</p></div></div>
    <details class="details"><summary>${t('Layout reference and depth control', '展开布局参考与深度控制图')}</summary><div class="content comparison model-reference">${image('reference', t('Blender reference', 'Blender 布局参考'), t('Original 512 × 512 reference; this is not a generated model result.', '原始 512 × 512 布局参考，不是模型生成结果。'))}${image('depth', t('Raw8 depth', 'Raw8 深度图'), t('Recorded 1024 × 1024 geometry control.', '记录中的 1024 × 1024 几何控制输入。'))}</div></details>
    <p class="caveat">${t('Qwen and FLUX are different generators: their columns must not be read as a single-model evolution chain. Qwen-Image-2512 plus this Depth ControlNet is an experimental pairing. The FLUX retry image hash is preserved in the archived report, but its raw evaluator/request files are not in this local package, so no per-case score or identical-parameter claim is published.', 'Qwen 与 FLUX 是不同生成模型，不能把它们串成同一模型的进化链。Qwen-Image-2512 与该 Depth ControlNet 是实验性搭配。FLUX 重试图的哈希保存在归档报告中，但本地包没有其原始逐项评测与请求文件，因此不展示逐例分数，也不声称其他参数完全相同。')}</p>
    <div class="evidence-links"><a href="model-cases.json" download>${t('Download model provenance ↓', '下载模型来源与证据 ↓')}</a><a href="model-cases.json" target="_blank" rel="noopener">${t('Inspect comparison record ↗', '查看对比记录 ↗')}</a></div><p class="source-id">${data.case_id} · ${t('Static curated comparison; separate from the trace API.', '静态精选对比，与 trace API 独立。')}</p>
  </section>`;
}
